### PR TITLE
fix(journey-maps): prevent console errors

### LINKED ISSUE #2080: [Bug]: Error: layers.xxx 'undefined' value invalid
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Other

### Which version are you using

16.8.0

### Operating system

Windows 10

### Browser / Browser version

Microsoft Edge

### Input mode

None

### Additional settings

_No response_

### What happened?

After updating the journey-maps library to 16.8.0, i see errors in the browser console regarding "undefined", e.g.:

`Error: layers.level-street-lvl.filter[1][2]: 'undefined' value invalid. Use null instead.`

The errors are also visible when opening the console on the SBB Angular Journey Maps Example page:
`https://sbb-angular.app.sbb.ch/journey-maps/components/angular/examples`

The errors do not occur with v16.7.1

### Steps to reproduce the issue

1. Update journey maps to 16.8.0
2. Check console

### Relevant log output

```shell
angular-WCVVIDOZ.js:1  Error: layers.level-street-k-lvl.filter[1][2]: 'undefined' value invalid. Use null instead.
    at Object.J4 [as emitValidationErrors] (angular-WCVVIDOZ.js:2:6906)
    at St (angular-WCVVIDOZ.js:2:346068)
    at Pi._validate (angular-WCVVIDOZ.js:2:368867)
    at Pi.setFilter (angular-WCVVIDOZ.js:2:362252)
    at Map.setFilter (angular-WCVVIDOZ.js:576:166014)
    at angular-WCVVIDOZ.js:714:11136
    at Array.forEach (<anonymous>)
    at w4.setLevelFilter (angular-WCVVIDOZ.js:714:11022)
    at Object.next (angular-WCVVIDOZ.js:714:15280)
    at e.next (chunk-UG3CQJHX.js:3:3966)
```

### PR DESCRIPTION
**Pull request by swiss-chris**
Fixes #2080

Refs: ROKAS-1766

### CODE REVIEW

**Review by mstankala — APPROVED** [review]
LGTM

**Review by mhaertwig — APPROVED** [review]
LGTM 👍
