### ISSUE TITLE
Bug: AutoComplete Error after Updating to 9.6.0

### ISSUE THREAD

**Issue by mghilardelli** [sbb-design-systems/sbb-angular#432]
**Describe the bug**
After updating SBB Angular to version 9.6.0 I have the following error when starting the app.
ERROR in node_modules/@sbb-esta/angular-public/autocomplete/autocomplete/autocomplete-trigger.directive.d.ts:6:13 - error TS1005: '=' expected.

6 import type import * as ɵngcc0 from '@angular/core';
              ~~~~~~
node_modules/@sbb-esta/angular-public/autocomplete/autocomplete/autocomplete-trigger.directive.d.ts:7:25 - error TS1005: ';' expected.

7 { FieldComponent } from '@sbb-esta/angular-public/field';
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@sbb-esta/angular-public/field/label/label.component.d.ts:1:13 - error TS1005: '=' expected.

1 import type import * as ɵngcc0 from '@angular/core';
              ~~~~~~
node_modules/@sbb-esta/angular-public/field/label/label.component.d.ts:2:25 - error TS1005: ';' expected.

2 { FieldComponent } from '../field/field.component';
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@sbb-esta/angular-public/field/form-field-token.d.ts:2:13 - error TS1005: '=' expected.

2 import type { FieldComponent } from './field/field.component';
              ~
node_modules/@sbb-esta/angular-public/field/form-field-token.d.ts:2:37 - error TS1005: ';' expected.

2 import type { FieldComponent } from './field/field.component';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@sbb-esta/angular-business/autocomplete/autocomplete/autocomplete-trigger.directive.d.ts:7:13 - error TS1005: '=' expected.

7 import type import * as ɵngcc0 from '@angular/core';
              ~~~~~~
node_modules/@sbb-esta/angular-business/autocomplete/autocomplete/autocomplete-trigger.directive.d.ts:8:25 - error TS1005: ';' expected.

8 { FieldComponent } from '@sbb-esta/angular-business/field';
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@sbb-esta/angular-business/field/label/label.component.d.ts:1:13 - error TS1005: '=' expected.

1 import type import * as ɵngcc0 from '@angular/core';
              ~~~~~~
node_modules/@sbb-esta/angular-business/field/label/label.component.d.ts:2:25 - error TS1005: ';' expected.

2 { FieldComponent } from '../field/field.component';
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@sbb-esta/angular-business/field/form-field-token.d.ts:3:13 - error TS1005: '=' expected.

3 import type { FieldComponent } from './field/field.component';
              ~
node_modules/@sbb-esta/angular-business/field/form-field-token.d.ts:3:37 - error TS1005: ';' expected.

3 import type { FieldComponent } from './field/field.component';

**To Reproduce**
1. Clone https://code.sbb.ch/scm/kd_cx/sbbgo-web.git
2. Checkout branch feature/SBBGOW-57-teilnehmende-screen
3. install and start

**Screenshots**
![image](https://user-images.githubusercontent.com/19152082/82827894-393db700-9eb0-11ea-8de8-4038b5a96e98.png)

**Comment by kyubisation** [comment]
Workaround is to update to Angular 9.1 and delete node_modules afterwards
`ng update @angular/cli @angular/core`
This should update TypeScript to version 3.8, which will work with version 9.6.0 of the library.
